### ISSUE TITLE
Null-pointer exception while loading tilesets

### ISSUE THREAD

**Issue by GoogleCodeExporter** [knilch0r/freeshisen#3]
```
java.lang.NullPointerException
at de.cwde.freeshisen.Tileset.loadPNGTileset(Tileset.java:22)
at de.cwde.freeshisen.Tileset.loadTileset(Tileset.java:87)
at de.cwde.freeshisen.ShisenShoView.loadTileset(ShisenShoView.java:153)
at de.cwde.freeshisen.ShisenShoView.initializeGame(ShisenShoView.java:160)
at de.cwde.freeshisen.ShisenShoView.repaint(ShisenShoView.java:260)
at de.cwde.freeshisen.ShisenShoView.surfaceCreated(ShisenShoView.java:582)
at android.view.SurfaceView.updateWindow(SurfaceView.java:563)
at android.view.SurfaceView.access$000(SurfaceView.java:83)
at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:172)
at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:590)
at android.view.ViewRoot.performTraversals(ViewRoot.java:1406)
at android.view.ViewRoot.handleMessage(ViewRoot.java:2040)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:132)
at android.app.ActivityThread.main(ActivityThread.java:4123)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:491)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
at dalvik.system.NativeStart.main(Native Method)
```

Original issue reported on code.google.com by `knilc...@gmail.com` on 27 Nov 2013 at 4:42

**Comment by knilch0r** [comment]
Not seen for a long time... Closing this one.
